name: EAS Update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Log in to Expo
        run: npx expo login --token ${{ secrets.EXPO_TOKEN }}

      - name: EAS update
        env:
          EXPO_PUBLIC_BACKEND_URL: ${{ secrets.EXPO_PUBLIC_BACKEND_URL }}
        run: npx eas update --branch main -m "Auto update from GitHub"
